genome: /home/danielle.perley/Ref/mm10.fa

samples: samples.txt

raw_data: raw_data

## path to nanopolish dir, relative to snakemake
nanopolish_path: "nanopolish"

resources:
  align:
    threads: 32
    time: 4:00:00
    mem: 100G
  call_meth:
    threads: 36
    time: 2-00:00:00
    mem: 100G
  
