genome: /home/danielle.perley/Ref/mm10.fa

samples: sample_sheet.txt

raw_data: raw_data

resources:
  align:
    threads: 32
  index_genome:  
    threads: 5
  call_meth:
    threads: 36
  samtools_sort:
    threads: 16  
