name: nanopolish2
channels:
    - conda-forge
    - bioconda
    - r 
    - defaults       
dependencies:
    - samtools =1.10
    - snakemake
    - minimap2 
    - pycoQC =2.5.0.23
    - pysam
    - pandas
    - multiqc
    - r-base=4.0.3
    - r-tidyverse=1.3
    - bioconductor-dss=2.36
    - bioconductor-bsseq=1.24
    - bioconductor-annotatr=1.14
    - bioconductor-chipseeker=1.26
    - bioconductor-do.db=2.9=r40_9
    - r-data.table=1.13
    - r-dtplyr
    - mamba
