name: nanopolish
channels:
    - conda-forge
    - bioconda
dependencies:
    - samtools =1.10
    - snakemake
    - minimap2
    - nanopolish 
    - pycoQC
    - pysam
    - pandas

## add pandas? and snakemake utils?

