name: nanopolish
channels:
    - bioconda
    - conda-forge        
dependencies:
    - samtools =1.10
    - snakemake
    - minimap2 
    - pycoQC =2.5.0.23
    - pysam
    - pandas

## add pandas? and snakemake utils?

